'use client';
import { useState } from 'react';
import products from '@/data/products.json';
import history from '@/data/price-history.json';
import { formatYen, recordsForProduct, summaryFor, type PriceRecord } from '@/lib/price-utils';
const records = history as PriceRecord[];
const dryingLabels: Record<string, string> = { heat_pump: 'ヒートポンプ乾燥', heater: 'ヒーター乾燥', low_temp_heater: '低温ヒーター乾燥', hybrid: 'ハイブリッド乾燥', unknown: '確認中' };
const doorLabels: Record<string, string> = { left: '左開き', right: '右開き', unknown: '開き方確認中' };
function PriceChart({ productId }: { productId: string }) { const points = recordsForProduct(records, productId); if (points.length < 2) return <p className="no-data">価格データ収集中です。</p>; const values = points.map((p) => p.price); const min = Math.min(...values); const max = Math.max(...values); const line = points.map((p, i) => `${5 + (i / (points.length - 1)) * 90},${84 - ((p.price - min) / Math.max(max - min, 1)) * 60}`).join(' '); return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="価格推移"><line x1="5" y1="84" x2="95" y2="84" /><polyline points={line} /></svg><div className="chart-label"><span>{formatYen(min)}</span><span>{formatYen(max)}</span></div></div>; }
function Detail({ product }: { product: (typeof products)[number] }) { const summary = summaryFor(recordsForProduct(records, product.id)); const latest = summary.current; const size = product.dimensions; return <div className="detail"><section><h3>価格の目安</h3><dl className="metrics"><div><dt>現在価格</dt><dd>{formatYen(latest?.price)}</dd></div><div><dt>30日平均</dt><dd>{formatYen(summary.average30)}</dd></div><div><dt>30日最安</dt><dd>{formatYen(summary.low30)}</dd></div><div><dt>90日最安</dt><dd>{formatYen(summary.low90)}</dd></div></dl><PriceChart productId={product.id} /></section><section className="specs"><h3>仕様</h3><dl><div><dt>サイズ</dt><dd>幅 {size.widthMm} × 奥行 {size.depthMm} × 高さ {size.heightMm} mm（{size.measurement === 'overall' ? '外形寸法' : 'ホース含む'}）</dd></div><div><dt>開き方</dt><dd>{doorLabels[product.doorDirection]}</dd></div><div><dt>洗乾電力</dt><dd>{product.washDryEnergyWh ? `${product.washDryEnergyWh} Wh / ${product.washDryTimeMinutes} 分` : '未公表'}</dd></div><div><dt>JAN</dt><dd>{product.janCode || '未登録'}</dd></div><div><dt>メモ</dt><dd>{product.notes}</dd></div></dl>{latest && <p className="latest-shop">最新: <a href={latest.url} target="_blank" rel="noreferrer">{latest.source} / {latest.shopName} ↗</a><br /><small>送料: {latest.shipping === 'included' ? '込み' : latest.shipping === 'excluded' ? '別' : '不明'}</small></p>}<a className="product-link" href={product.officialUrl} target="_blank" rel="noreferrer">メーカー公式ページ ↗</a></section></div>; }
export default function DrumWatchClient() { const [expandedId, setExpandedId] = useState<string | null>(products[0]?.id ?? null); return <main><header className="topbar"><div><p className="eyebrow">DRUM WATCH / PERSONAL PRICE TRACKER</p><h1>ドラム式、いまが買い時？</h1></div><p className="update">2人暮らし向け · 8kg以上 / 乾燥あり<br />価格データは収集中</p></header><section className="intro"><div><p className="section-label">比較中のモデル</p><h2>価格を先に、暮らしやすさを次に。</h2></div><p>メーカー公式仕様で確認した候補です。価格を取得後、商品ごと・日ごとの最安価格を記録します。</p></section><section className="watchlist" aria-label="商品一覧"><div className="table-head"><span>機種</span><span>現在の最安価格</span><span>前回比</span><span>30日最安</span><span>容量・乾燥</span><span>判定</span></div>{products.map((product) => { const summary = summaryFor(recordsForProduct(records, product.id)); const expanded = expandedId === product.id; return <article className={`product ${expanded ? 'expanded' : ''}`} key={product.id}><button className="product-row" onClick={() => setExpandedId(expanded ? null : product.id)} aria-expanded={expanded}><span className="product-name"><strong>{product.productName}</strong><small>{product.manufacturer} · {product.model} · {doorLabels[product.doorDirection]}</small></span><span className="price">{summary.current ? formatYen(summary.current.price) : '価格データ収集中'}<small>{summary.current?.shipping === 'included' ? '送料込み' : summary.current ? '送料不明を含む' : '初回取得待ち'}</small></span><span className={summary.difference && summary.difference < 0 ? 'diff down' : 'diff'}>{summary.difference === undefined ? '—' : `${summary.difference > 0 ? '+' : ''}${formatYen(summary.difference)}`}</span><span>{summary.low30 === undefined ? '—' : formatYen(summary.low30)}</span><span>{product.washCapacityKg}kg / {product.dryCapacityKg}kg<small>{dryingLabels[product.dryingMethod]} · 自動投入 {product.autoDosing === null ? '確認中' : product.autoDosing ? 'あり' : 'なし'}</small></span><span><b className={`timing ${summary.current ? summary.buyTiming : ''}`}>{summary.current ? summary.buyTiming : '収集中'}</b><i>{expanded ? '−' : '+'}</i></span></button>{expanded && <Detail product={product} />}</article>; })}</section><footer><p>価格履歴はAPI設定後に蓄積されます。メーカーが未公表の仕様は「未登録」または「確認中」と表示します。</p><div className="rakuten-credit" dangerouslySetInnerHTML={{ __html: '<!-- Rakuten Web Services Attribution Snippet FROM HERE -->\n<a href="https://developers.rakuten.com/" target="_blank">Supported by Rakuten Developers</a>\n<!-- Rakuten Web Services Attribution Snippet TO HERE -->' }} /></footer></main>; }
